name: Docker Setup Test
on: [push]
jobs:
  mac_nix:
    strategy:
      matrix:
        os: [ubuntu-latest] # , macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Run Docker unit tests
        run: |
          ./go.sh run-docker-desktop-unit-test
      - name: Run Docker integration tests
        run: |
          ./go.sh run-docker-desktop-integration-test

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Run Docker unit tests
        run: |
          .\go.ps1 run-docker-desktop-unit-test
      - name: Run Docker integration tests
        run: |
          .\go.ps1 run-docker-desktop-integration-test
